sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pranavsingh91/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pranavsingh91/react-test npm test

after_success:
  - docker build -t pranavsingh91/multi-client ./client
  - docker build -t pranavsingh91/multi-nginx ./nginx
  - docker build -t pranavsingh91/multi-server ./server
  - docker build -t pranavsingh91/multi-worker ./worker
